#!/bin/bash

cwd=$(pwd)
configDir=$HOME/.config
mkdir -p $configDir

symlink () {
    if [ ! -x "$2" ]; then
        ln -snvf "$1" "$2"
    fi
}

symlink "$cwd/home/config/tmux"         "$HOME/.config/tmux"
symlink "$cwd/home/config/wezterm"      "$HOME/.config/wezterm"
symlink "$cwd/home/config/vim"          "$HOME/.config/vim"
symlink "$cwd/home/config/bash"         "$HOME/.config/bash"
symlink "$cwd/home/config/surf"         "$HOME/.config/surf"

symlink "$cwd/home/config/vim/vimrc"    "$HOME/.vimrc"
symlink "$cwd/home/config/bash/profile" "$HOME/.profile"
symlink "$cwd/home/config/bash/bashrc"  "$HOME/.bashrc"

symlink "$cwd/home/local/bin/dmenu/passmenu" "$HOME/.local/bin/passmenu"
symlink "$cwd/home/local/bin/dmenu/mathmenu" "$HOME/.local/bin/mathmenu"
symlink "$cwd/home/local/bin/dmenu/manmenu" "$HOME/.local/bin/manmenu"
