set -g default-terminal "tmux-256color"
# Enable CSI u mode and extended keys
# set -g extended-keys on
# set -as terminal-features 'wezterm:extkeys'
# set -g default-terminal "tmux-256color"
# set -as terminal-overrides ',*:Tc'

set -g base-index 1
setw -g pane-base-index 1
set-option -g renumber-windows on

set -g status-position top

bind '\' split-window -h
bind '/' split-window -v
unbind '"'
unbind %
