# If not running interactively, don't do anything
case $- in
    *i*) ;;
      *) return;;
esac

shopt -s histappend
shopt -s checkwinsize
shopt -s direxpand

[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"

[[ -x $(which dircolors 2> /dev/null) ]] && eval "$(dircolors -b)"

. $HOME/.config/bash/env
. $HOME/.config/bash/complete
. $HOME/.config/bash/prompt
. $HOME/.config/bash/alias

[[ -x $(which scent 2> /dev/null) ]] && scent
